# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SplashScreen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'lottie-ios'

  # Pods for SplashScreen

  target 'SplashScreenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SplashScreenUITests' do
    # Pods for testing
  end

end
