# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quiz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Firestore'

# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'

  # Pods for Quiz

  target 'QuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuizUITests' do
    # Pods for testing
  end

end
