# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Login_Face_ID' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Auth'

  # Pods for Login_Face_ID

  target 'Login_Face_IDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Login_Face_IDUITests' do
    # Pods for testing
  end

end
