# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DLogin

pod 'Firebase/Auth'

  target 'DLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DLoginUITests' do
    # Pods for testing
  end

end
